//
//  SANAdSize.h
//  SAN SDK
//
//  Copyright 2021 SAN LLC. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "SANMobileAdsDefines.h"

/// A valid SANAdSize is considered to be one of the predefined SANAdSize constants or a SANAdSize
/// constructed by SANAdSizeFromCGSize, SANAdSizeFullWidthPortraitWithHeight,
/// SANAdSizeFullWidthLandscapeWithHeight.
///
/// Do not create a SANAdSize manually. Use one of the kSANAdSize constants. Treat SANAdSize as an
/// opaque type. Do not access any fields directly. To obtain a concrete CGSize, use the function
/// CGSizeFromSANAdSize().
typedef struct SAN_BOXABLE SANAdSize SANAdSize;

/// Ad size.
///
/// @see typedef SANAdSize
struct SAN_BOXABLE SANAdSize {
  /// The ad size. Don't modify this value directly.
  CGSize size;
  /// Reserved.
  NSUInteger flags;
};

#pragma mark Standard Sizes

/// iPhone and iPod Touch ad size. Typically 320x50.
SAN_EXTERN SANAdSize const kSANAdSizeBanner;

/// Taller version of kSANAdSizeBanner. Typically 320x100.
SAN_EXTERN SANAdSize const kSANAdSizeLargeBanner;

/// Medium Rectangle size for the iPad (especially in a UISplitView's left pane). Typically 300x250.
SAN_EXTERN SANAdSize const kSANAdSizeMediumRectangle;

/// Full Banner size for the iPad (especially in a UIPopoverController or in
/// UIModalPresentationFormSheet). Typically 468x60.
SAN_EXTERN SANAdSize const kSANAdSizeFullBanner;

/// Leaderboard size for the iPad. Typically 728x90.
SAN_EXTERN SANAdSize const kSANAdSizeLeaderboard;

/// Skyscraper size for the iPad. Mediation only. SAN does not offer this size. Typically
/// 120x600.
SAN_EXTERN SANAdSize const kSANAdSizeSkyscraper;

/// An ad size that spans the full width of its container, with a height dynamically determined by
/// the ad.
SAN_EXTERN SANAdSize const kSANAdSizeFluid;

/// Invalid ad size marker.
SAN_EXTERN SANAdSize const kSANAdSizeInvalid;

#pragma mark Adaptive Sizes

/// Returns a SANAdSize with the given width and a SAN-optimized height to create a banner ad.
/// The size returned has an aspect ratio similar to that of kSANAdSizeBanner, suitable for
/// anchoring near the top or bottom of your app. The height is never larger than 15% of the
/// device's portrait height and is always between 50-90 points. This function always returns the
/// same height for any width / device combination.
SAN_EXTERN SANAdSize SANPortraitAnchoredAdaptiveBannerAdSizeWithWidth(CGFloat width);

/// Returns a SANAdSize with the given width and a SAN-optimized height to create a banner ad.
/// The size returned is suitable for use in a banner ad anchored near the top or bottom of your
/// app, similar to use of kSANAdSizeBanner. The height is never larger than 15% of the devices's
/// landscape height and is always between 50-90 points. This function always returns the same
/// height for any width / device combination.
SAN_EXTERN SANAdSize SANLandscapeAnchoredAdaptiveBannerAdSizeWithWidth(CGFloat width);

/// Returns a SANAdSize with the given width and a SAN-optimized height. This is a convenience
/// function to return SANPortraitAnchoredAdaptiveBannerAdSizeWithWidth or
/// SANLandscapeAnchoredAdaptiveBannerAdSizeWithWidth based on the current interface orientation.
/// This function must be called on the main queue.
SAN_EXTERN SANAdSize SANCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(CGFloat width);

#pragma mark Custom Sizes

/// Returns a custom SANAdSize for the provided CGSize. Use this only if you require a non-standard
/// size. Otherwise, use one of the standard size constants above.
SAN_EXTERN SANAdSize SANAdSizeFromCGSize(CGSize size);

/// Returns a custom SANAdSize that spans the full width of the application in portrait orientation
/// with the height provided.
SAN_EXTERN SANAdSize SANAdSizeFullWidthPortraitWithHeight(CGFloat height);

/// Returns a custom SANAdSize that spans the full width of the application in landscape orientation
/// with the height provided.
SAN_EXTERN SANAdSize SANAdSizeFullWidthLandscapeWithHeight(CGFloat height);

#pragma mark Convenience Functions

/// Returns YES if the two SANAdSizes are equal, otherwise returns NO.
SAN_EXTERN BOOL SANAdSizeEqualToSize(SANAdSize size1, SANAdSize size2);

/// Returns a CGSize for the provided a SANAdSize constant. If the SANAdSize is unknown, returns
/// CGSizeZero.
SAN_EXTERN CGSize CGSizeFromSANAdSize(SANAdSize size);

/// Returns YES if |size| is one of the predefined constants or is a custom SANAdSize generated by
/// SANAdSizeFromCGSize.
SAN_EXTERN BOOL IsSANAdSizeValid(SANAdSize size);

/// Returns YES if |size| is a fluid ad size.
SAN_EXTERN BOOL SANAdSizeIsFluid(SANAdSize size);

/// Returns a NSString describing the provided SANAdSize.
SAN_EXTERN NSString *_Nonnull NSStringFromSANAdSize(SANAdSize size);

/// Returns an NSValue representing the SANAdSize.
SAN_EXTERN NSValue *_Nonnull NSValueFromSANAdSize(SANAdSize size);

/// Returns a SANAdSize from an NSValue. Returns kSANAdSizeInvalid if the value is not a SANAdSize.
SAN_EXTERN SANAdSize SANAdSizeFromNSValue(NSValue *_Nonnull value);

#pragma mark Deprecated

/// An ad size that spans the full width of the application in portrait orientation. The height is
/// typically 50 points on an iPhone/iPod UI, and 90 points tall on an iPad UI.
SAN_EXTERN SANAdSize const kSANAdSizeSmartBannerPortrait
    SAN_DEPRECATED_MSG_ATTRIBUTE("Use SANPortraitAnchoredAdaptiveBannerAdSizeWithWidth.");

/// An ad size that spans the full width of the application in landscape orientation. The height is
/// typically 32 points on an iPhone/iPod UI, and 90 points tall on an iPad UI.
SAN_EXTERN SANAdSize const kSANAdSizeSmartBannerLandscape
    SAN_DEPRECATED_MSG_ATTRIBUTE("Use SANLandscapeAnchoredAdaptiveBannerAdSizeWithWidth");
